### ISSUE TITLE
Too similar code 

### ISSUE THREAD

**Issue by IanaKhitsko** [dmmaks/MIPZ_lab1#2]
These code blocks 
https://github.com/dmmaks/MIPZ_lab1/blob/333681c39e42167b62dfc6eb906f9685c77f86cf/src/main/java/org/example/Renju.java#L46-L55

and 

https://github.com/dmmaks/MIPZ_lab1/blob/333681c39e42167b62dfc6eb906f9685c77f86cf/src/main/java/org/example/Renju.java#L57-L66

.. and other 2 look similar. Could you please consider combining the logic into one method/template method/lambda/etc. ?

**Comment by dmmaks** [comment]
Extarcted two methods
