### ISSUE TITLE
Move from the 'main' method to some other (create one)

### ISSUE THREAD

**Issue by StepanenkoAndrii** [dmmaks/MIPZ_lab1#6]
https://github.com/dmmaks/MIPZ_lab1/blob/333681c39e42167b62dfc6eb906f9685c77f86cf/src/main/java/org/example/Renju.java#L15-L32

**Comment by dmmaks** [comment]
Moved most code from main into separate method

**Comment by StepanenkoAndrii** [comment]
Issue solved, no further issues found
